# Generated by Django 5.1.4 on 2024-12-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='listening_audio/')),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
    ]
